/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vista_grafico;

import com.mycompany.modelo_grafico.Usuario;
import javax.swing.JMenu;
import javax.swing.JPanel;

/**
 *
 * @author Dam
 */
public class Vista_MiVentana extends javax.swing.JFrame {
    
    private Usuario usuarioActual;
    
    JPanel panelActivo;
    Vista_MiPanel_Inicio miPanelInicio;
    
    /**
     * Creates new form Vista_MiVentana
     */
    public Vista_MiVentana() {
        initComponents();
        
        miPanelInicio = new Vista_MiPanel_Inicio(this);
        
        panelActivo = miPanelInicio;
        
        this.getContentPane().add(panelActivo);
        panelActivo.setSize(this.getSize());
        panelActivo.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBarra = new javax.swing.JMenuBar();
        menuOpciones = new javax.swing.JMenu();
        menuNuevo = new javax.swing.JMenuItem();
        menuActualizar = new javax.swing.JMenuItem();
        menuBorrar = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenu();
        menuUsuarioCambiar = new javax.swing.JMenuItem();
        menuUsuarioNuevo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuOpciones.setText("Opciones");

        menuNuevo.setText("Nuevo");
        menuNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNuevoActionPerformed(evt);
            }
        });
        menuOpciones.add(menuNuevo);

        menuActualizar.setText("Actualizar");
        menuActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActualizarActionPerformed(evt);
            }
        });
        menuOpciones.add(menuActualizar);

        menuBorrar.setText("Borrar");
        menuBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBorrarActionPerformed(evt);
            }
        });
        menuOpciones.add(menuBorrar);

        menuBarra.add(menuOpciones);

        menuUsuarios.setText("Usuarios");

        menuUsuarioCambiar.setText("Cambiar");
        menuUsuarioCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuarioCambiarActionPerformed(evt);
            }
        });
        menuUsuarios.add(menuUsuarioCambiar);

        menuUsuarioNuevo.setText("Nuevo");
        menuUsuarios.add(menuUsuarioNuevo);

        menuBarra.add(menuUsuarios);

        setJMenuBar(menuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNuevoActionPerformed
        // TODO add your handling code here:
        
        this.cambiarPanel(new Vista_MiPanel_Nuevo(this));
        
    }//GEN-LAST:event_menuNuevoActionPerformed

    private void menuActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActualizarActionPerformed
        // TODO add your handling code here:
        
        this.cambiarPanel(new Vista_MiPanel_Actualizar(this));
        
    }//GEN-LAST:event_menuActualizarActionPerformed

    private void menuBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBorrarActionPerformed
        // TODO add your handling code here:
        
        this.cambiarPanel(new Vista_MiPanel_Borrar(this));
        
    }//GEN-LAST:event_menuBorrarActionPerformed

    private void menuUsuarioCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuarioCambiarActionPerformed
        // TODO add your handling code here:
        
        this.cambiarPanel(new Vista_MiPanel_Usuario(this));
        
    }//GEN-LAST:event_menuUsuarioCambiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_MiVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_MiVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_MiVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_MiVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_MiVentana().setVisible(true);
            }
        });
    }
    
    public void cambiarPanel(JPanel panel){
        
        panelActivo.setVisible(false);
        this.getContentPane().remove(panelActivo);
        panelActivo = panel;
        this.getContentPane().add(panelActivo);
        panelActivo.setSize(this.getSize());
        panelActivo.setVisible(true);
        panelActivo.updateUI();
        
    }
    
    public void setMenuOculto(){
        this.menuOpciones.setVisible(false);
    }
    
    public void setMenuVisible(){
        this.menuOpciones.setVisible(true);
    }
    
    public Usuario getUsuarioActual(){
        return this.usuarioActual;
    }
    
    public void setUsuarioActual(Usuario usuario){
        this.usuarioActual = usuario;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem menuActualizar;
    private javax.swing.JMenuBar menuBarra;
    private javax.swing.JMenuItem menuBorrar;
    private javax.swing.JMenuItem menuNuevo;
    private javax.swing.JMenu menuOpciones;
    private javax.swing.JMenuItem menuUsuarioCambiar;
    private javax.swing.JMenuItem menuUsuarioNuevo;
    private javax.swing.JMenu menuUsuarios;
    // End of variables declaration//GEN-END:variables
}
